### ISSUE TITLE
Details on meaning of `server.mode` setting

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#121]
Effects of the meaning of the `server.mode` setting values `development`, `test` and `production` need to be added.

Maybe using a table?

**Comment by lvca** [comment]
The main difference, right now, it's in the output messages. When not in production mode, stack trace for an exception on the server is not printed in the console. Also, in production Studio is not available (the underlying HTTP dynamic content handler is not installed).

So:

```
development = studio available, higher trace of server logs
test = studio available, less logging on the server
production = studio not available, less logging on the server
```

I'm open to ideas where we could use this setting to change other behavior of ArcadeDB.

**Comment by gramian** [comment]
Added in https://github.com/ArcadeData/arcadedb-docs/commit/21e0fba356736eb5585c1d72ceea089f7859934d .
