### ISSUE TITLE
Clojure Example for Embedded Server

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#127]
Add a minimal example on how to use ArcadeDB server as embedded server in Clojure.

**Comment by littleli** [comment]
Minimal example is available https://github.com/littleli/embed-arcadedb-clojure

it boils down to this piece:

```clojure
(ns demo
  (:import [com.arcadedb ContextConfiguration]
           [com.arcadedb.server ArcadeDBServer])
  (:gen-class))

(comment

  (def config (ContextConfiguration.))
  (def server (ArcadeDBServer. config))
  (.start server)

  (def db (.getOrCreateDatabase server "demo.db"))
  db

,)
```

It's based on Java embedding example in the documentation.
