### ISSUE TITLE
Introduction : Multi-Model : Key/Value Model mentions HTTP calls that do not appear to be supported

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb-docs#19]
The documentation mentions that the "typeic" (is this meant to be the word "typical"?) use cases are to make HTTP calls to endpoints that do not appear to be registered in `com.arcadedb.server.http.HttpServer`.

Are there HTTP equivalent endpoints for the operations on the Key/Value model, or is only using the Redis driver supported?

**Comment by lvca** [comment]
Please check out the updated documentation about the supported Redis Commands and their usage:

https://docs.arcadedb.com/#Redis-API

You can use HTTP API to do pretty much the same, by using SQL:

https://docs.arcadedb.com/#HTTP-Command

You can use at the same time the Redis API, HTTP, MongoDB and Postgres protocol on the same database.
