### ISSUE TITLE
Documentation for Arcadedb Exception to help client library exception report

### ISSUE THREAD

**Issue by eisenhaus335** [ArcadeData/arcadedb-docs#198]
I am writing for arcadedb client library in python. Currently, arcadedb document has not own section for Exceptions Handling and Error message and status code. Providing details for Exceptions will be helpful to write meaningful error status and code

I also follow this PEP specification for database, somewhat. Maybe for start we could follow this exceptions labels
https://peps.python.org/pep-0249/#exceptions

**Comment by gramian** [comment]
Hi @eisenhaus335 ,
I updated the [HTTP API](https://docs.arcadedb.com/#HTTP-API) section of the docs. Could you take a look at the endpoint description, and give some feedbackon what you are missing?
Thanks

**Comment by eisenhaus335** [comment]
@gramian Yes. Thank you. I think its suffice for now. It should help. I will make another issue if i need further addition
