### ISSUE TITLE
HTTP endpoints and commands summary

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#45]
Dear Developers,

would you consider to add a section to the appendix summarizing the HTTP endpoints and JSON parameters in tables?
Below, I attempted a draft of this:

| Action                                                               | Method | Endpoint                                 |
|----------------------------------------------------------------------|--------|------------------------------------------|
| [Execute a command](https://docs.arcadedb.com/#HTTP-Command)         | POST   | `/api/v1/command/{database}`             |
| [Commit a transaction](https://docs.arcadedb.com/#HTTP-Commit)       | POST   | `/api/v1/commit/{database}`              |
| [Create a database](https://docs.arcadedb.com/#HTTP-CreateDatabase)  | POST   | `/api/v1/create/{database}`              |
| [List of databases](https://docs.arcadedb.com/#HTTP-ListDatabases)   | GET    | `/api/v1/databases`                      |
| [Create a document](https://docs.arcadedb.com/#HTTP-CreateDocument)  | POST   | `/api/v1/document/{database}`            |
| [Load a document](https://docs.arcadedb.com/#HTTP-LoadDocument)      | GET    | `/api/v1/document/{database}/{rid}`      |
| [Open a database](https://docs.arcadedb.com/#HTTP-OpenDatabase)      | POST   | `/api/v1/open/{database}`                |
| [Close a database](https://docs.arcadedb.com/#HTTP-CloseDatabase)    | POST   | `/api/v1/close/{database}`               |
| [Drop a database](https://docs.arcadedb.com/#HTTP-DropDatabase)      | POST   | `/api/v1/drop/{database}`                |
| [Execute a query](https://docs.arcadedb.com/#HTTP-ExecuteQuery)      | GET    | `/api/v1/query/{database}`               |
| [Execute SQL query](https://docs.arcadedb.com/#HTTP-ExecuteQuery)    | GET    | `/api/v1/query/{database}/sql/{command}` |
| [Rollback a transaction](https://docs.arcadedb.com/#HTTP-Rollback)   | POST   | `/api/v1/rollback/{database}`            |
| [Get server information](https://docs.arcadedb.com/#HTTP-ServerInfo) | GET    | `/api/v1/server`                         |

| Parameters | Type     | Values                                          |
|------------|----------|-------------------------------------------------|
| language   | Required | "sql", "cypher", "gremlin", "neo4j", and others |
| command    | Required | encoded command string                          |
| limit      | Optional | maximum number of results                       |
| params     | Optional | map of parameters                               |
| serializer | Optional | "graph", "record"                               |

**Comment by gramian** [comment]
Hi,
when looking through the doc sources I was unsure if you are using a some integrated system to generate the docs, so that manual changes to the source would not actually help you. I will make PRs in the future.

Best

**Comment by lvca** [comment]
It's already online: https://docs.arcadedb.com/#_reference. Thanks!
