### ISSUE TITLE
HTTP/JSON Examples

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#47]
The examples in Section [7.2 HTTP/JSON Protocol](https://docs.arcadedb.com/#HTTP-API) use as credentials for `curl`:
```
--user root:root
```
Yet, "root" would be too short as a password for ArcadeDB (Minimum 8 characters). Should this be changed to fit this?

**Comment by lvca** [comment]
Yep, I've just updated the docs, will be online in 10 minutes. Thanks!
