### ISSUE TITLE
query language endpoint

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#49]
Dear Developers,

could you please check the documentation for the query language endpoints? In Section 7.2 (HTTP/JSON protocol) it is stated that the endpoint syntax
```
/api/v1/query/{database}/{language}/{command}
```
is only supported for "sql" (see [URL Syntax 2](https://docs.arcadedb.com/#HTTP-ExecuteQuery)). However, in Sections [7.8 (Open Cypher)](https://docs.arcadedb.com/#_open-cypher), [7.9 (Gremlin API)](https://docs.arcadedb.com/#Gremlin-API), [7.10 (GraphQL)](https://docs.arcadedb.com/#_graphql), [7.11 (MongoDB API)](https://docs.arcadedb.com/#MongoDB-API) examples use this syntax as opposed to stating the language in the payload data `"language"` field. Are the examples correct or the statement in Section 7.2, or did I misinterpret something?

Starting the server `mongo`, `gremlin`, `cypher`, `graphql`, and `sql` are listed as available query languages. So if this is correct, the listed languages in Section 7.2 for "[Execute a command (POST)](https://docs.arcadedb.com/#HTTP-Command)" and "[Execute a query (GET)](https://docs.arcadedb.com/#HTTP-ExecuteQuery)" would also need updating by adding `mongo` and `graphql`.

Thanks for the clarifications

**Comment by lvca** [comment]
The HTTP query supports any query language installed. Are you sure the respective query language are installed?

Could you please post the server logs?

Also, what's the error when you try to execute the query?

Have you also tried the PSOT `/command`?

**Comment by gramian** [comment]
I was just referring to the details in the documentation. Sorry for not being clear.

**Comment by gramian** [comment]
PS: Is `"neo4j"` in Section 7.2 for "[Execute a command (POST)](https://docs.arcadedb.com/#HTTP-Command)" and "[Execute a query (GET)](https://docs.arcadedb.com/#HTTP-ExecuteQuery)" supposed to be `"graphql"`?

**Comment by lvca** [comment]
@gramian sorry I misread that. Thanks for the clarification, docs are fixed. Will be online in 10 mins.

**Comment by gramian** [comment]
@lvca One other thing I noticed in Section 7.2, "[Execute a query (GET)](https://docs.arcadedb.com/#HTTP-ExecuteQuery)" is that both examples use a POST, but it should be GET, right **?** And additionally, in the first example of this section the endpoint should be `query` instead of `command`.

**Comment by lvca** [comment]
@gramian you're right, fixed. Online in about 10 mins. Thanks!
