### ISSUE TITLE
Create new chapter about User/Group server API

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb-docs#51]
### Discussed in https://github.com/ArcadeData/arcadedb/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **gramian** October  1, 2022</sup>
Dear Community,

how does one create a new user? OrientDB has a SQL command `CREATE USER <user> IDENTIFIED BY <password>`, this seems not to work here. I also did not find a syntax for the console, a button in the studio, or a command-line setting for the server.

Thanks</div>

**Comment by gramian** [comment]
Thank you for the explanation.

But there is no way of creating a non-root user from the console?

**Comment by lvca** [comment]
It would be useful having an API on the server to manage users + some commands from the console to use them. Could you please create a new issue on the main repository for this? Thanks, @gramian.
