### ISSUE TITLE
Docker registry page fixes and additions (and on the website)

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb-docs#71]
I post the following here, as these are documentation issues, just not inside the documentation itself. The points below refer to Docker registry page https://registry.hub.docker.com/r/arcadedata/arcadedb . The first is a fix for the `docker run` command, the others are improvements other popular containers features (see for example https://registry.hub.docker.com/_/hello-world )

* [x] In the Docker example (under "Getting started in 5 minuted") the environment parameters:
```
-e arcadedb.server.rootPassword=playwithdata
-e "arcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
```
need to be changed to
```
-e JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata"
-e JAVA_OPTS="-Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
```

* [x] Add website http://arcadedb.com to overview (as there is no link on the overview page to the ArcadeDB project)
* [ ] Add note of the base container of the ArcadeDB container (if applicable)
* [x] Add a "**Maintained by:** [ArcadeData](https://arcadedata.com/)" (or alike)
* [x] Add a "**Where to get help:** [ArcadeDB Discussions](https://github.com/ArcadeData/arcadedb/discussions)" (or alike)
* [x] Add a "**Where to file issues:** [ArcadeDB Issues](https://github.com/ArcadeData/arcadedb/issues)" 
* [ ] Add [avatar icon](https://pbs.twimg.com/profile_images/1435658382703316996/_QqYRZAa_400x400.png) as container icon

PS: 
* [x] The Docker example on the ArcadeDB website also needs a change from:
```
-e arcadedb.server.rootPassword=playwithdata
```
to:
```
-e JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata"
```
* [ ] The copyright year on the ArcadeDB website is still 2021 (The copyright year on the ArcadeData website is still 2019).

**Comment by lvca** [comment]
About the copyright year, should be the 1st year of publishing, so they are both correct.

What do you mean with "Add note of the base container of the ArcadeDB container (if applicable)"?

Not sure how to update the docker icon

**Comment by gramian** [comment]
> About the copyright year, should be the 1st year of publishing, so they are both correct.

Sorry, I wrongfully assumed it should be updated with the date of the latest change, but Stackoverflow is disagreeing.

> What do you mean with "Add note of the base container of the ArcadeDB container (if applicable)"?

In case the container is derived from another container, this information maybe useful to the user; I guess it is not applicable.

> Not sure how to update the docker icon

I assumed it was just a drag and drop thing as for other platforms.

**Comment by gramian** [comment]
@lvca The example on the website did not update for me yet, otherwise this issue can be closed.

**Comment by lvca** [comment]
It's updated for me. Please try to clear the cache or do CTRL + F5 (on Mac)

**Comment by lvca** [comment]
![image](https://user-images.githubusercontent.com/312606/197085859-bca645b3-05e5-4504-91d4-92d3e705831c.png)

**Comment by gramian** [comment]
Sorry, I did not report correctly, I should have said: In the first line of the `docker` command it still says:
```
-e arcadedb.server.rootPassword=playwithdata
```
I think this environment variable needs to be put in to `JAVA_OPTS` too, as in the docs: [Quick Start Docker](https://docs.arcadedb.com/#Quick-Start-Docker). So it should say:
```
JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata \
-Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
```
or similar.

**Comment by lvca** [comment]
@gramian you're right I haven't noticed the previous env. Fixed now. It should be online in 5 mins. Thanks.
