### ISSUE TITLE
Graceful shutdown of embedded server

### ISSUE THREAD

**Issue by gfinger** [ArcadeData/arcadedb-docs#99]
Is it possible to shutdown an embedded server gracefully? When I kill my server (Ctrl-C) the database remains locked, so that there the next start of the server gives me the warning that the database was not closed properly.

**Comment by gramian** [comment]
Hi,
local CTRL+C shutdown is included in the next release 23.1.1 as by https://github.com/ArcadeData/arcadedb/commit/b1170971f34667c1d44fb5ab9807a4051ccd3cf6
and furthermore, remote shutdown is proposed here: https://github.com/ArcadeData/arcadedb/issues/722
Best

**Comment by gfinger** [comment]
this should solve the issue, thank you
